use crate::vkinit::pipeline::VertexDat;

// Generated by Claude Sonnet 4.6!!! (claude.ai) >>
pub fn cube() -> Vec<VertexDat> {
    vec![
        // Front — red
        VertexDat { position: [-0.5, -0.5,  0.5], uv: [0.0, 0.0], color: [1.0, 0.0, 0.0] },
        VertexDat { position: [ 0.5, -0.5,  0.5], uv: [1.0, 0.0], color: [1.0, 0.0, 0.0] },
        VertexDat { position: [ 0.5,  0.5,  0.5], uv: [1.0, 1.0], color: [1.0, 0.0, 0.0] },
        VertexDat { position: [-0.5, -0.5,  0.5], uv: [0.0, 0.0], color: [1.0, 0.0, 0.0] },
        VertexDat { position: [ 0.5,  0.5,  0.5], uv: [1.0, 1.0], color: [1.0, 0.0, 0.0] },
        VertexDat { position: [-0.5,  0.5,  0.5], uv: [0.0, 1.0], color: [1.0, 0.0, 0.0] },

        // Back — green
        VertexDat { position: [ 0.5, -0.5, -0.5], uv: [0.0, 0.0], color: [0.0, 1.0, 0.0] },
        VertexDat { position: [-0.5, -0.5, -0.5], uv: [1.0, 0.0], color: [0.0, 1.0, 0.0] },
        VertexDat { position: [-0.5,  0.5, -0.5], uv: [1.0, 1.0], color: [0.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5, -0.5, -0.5], uv: [0.0, 0.0], color: [0.0, 1.0, 0.0] },
        VertexDat { position: [-0.5,  0.5, -0.5], uv: [1.0, 1.0], color: [0.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5,  0.5, -0.5], uv: [0.0, 1.0], color: [0.0, 1.0, 0.0] },

        // Left — blue
        VertexDat { position: [-0.5, -0.5, -0.5], uv: [0.0, 0.0], color: [0.0, 0.0, 1.0] },
        VertexDat { position: [-0.5, -0.5,  0.5], uv: [1.0, 0.0], color: [0.0, 0.0, 1.0] },
        VertexDat { position: [-0.5,  0.5,  0.5], uv: [1.0, 1.0], color: [0.0, 0.0, 1.0] },
        VertexDat { position: [-0.5, -0.5, -0.5], uv: [0.0, 0.0], color: [0.0, 0.0, 1.0] },
        VertexDat { position: [-0.5,  0.5,  0.5], uv: [1.0, 1.0], color: [0.0, 0.0, 1.0] },
        VertexDat { position: [-0.5,  0.5, -0.5], uv: [0.0, 1.0], color: [0.0, 0.0, 1.0] },

        // Right — yellow
        VertexDat { position: [ 0.5, -0.5,  0.5], uv: [0.0, 0.0], color: [1.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5, -0.5, -0.5], uv: [1.0, 0.0], color: [1.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5,  0.5, -0.5], uv: [1.0, 1.0], color: [1.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5, -0.5,  0.5], uv: [0.0, 0.0], color: [1.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5,  0.5, -0.5], uv: [1.0, 1.0], color: [1.0, 1.0, 0.0] },
        VertexDat { position: [ 0.5,  0.5,  0.5], uv: [0.0, 1.0], color: [1.0, 1.0, 0.0] },

        // Top — cyan
        VertexDat { position: [-0.5,  0.5,  0.5], uv: [0.0, 0.0], color: [0.0, 1.0, 1.0] },
        VertexDat { position: [ 0.5,  0.5,  0.5], uv: [1.0, 0.0], color: [0.0, 1.0, 1.0] },
        VertexDat { position: [ 0.5,  0.5, -0.5], uv: [1.0, 1.0], color: [0.0, 1.0, 1.0] },
        VertexDat { position: [-0.5,  0.5,  0.5], uv: [0.0, 0.0], color: [0.0, 1.0, 1.0] },
        VertexDat { position: [ 0.5,  0.5, -0.5], uv: [1.0, 1.0], color: [0.0, 1.0, 1.0] },
        VertexDat { position: [-0.5,  0.5, -0.5], uv: [0.0, 1.0], color: [0.0, 1.0, 1.0] },

        // Bottom — pink
        VertexDat { position: [-0.5, -0.5, -0.5], uv: [0.0, 0.0], color: [1.0, 0.0, 1.0] },
        VertexDat { position: [ 0.5, -0.5, -0.5], uv: [1.0, 0.0], color: [1.0, 0.0, 1.0] },
        VertexDat { position: [ 0.5, -0.5,  0.5], uv: [1.0, 1.0], color: [1.0, 0.0, 1.0] },
        VertexDat { position: [-0.5, -0.5, -0.5], uv: [0.0, 0.0], color: [1.0, 0.0, 1.0] },
        VertexDat { position: [ 0.5, -0.5,  0.5], uv: [1.0, 1.0], color: [1.0, 0.0, 1.0] },
        VertexDat { position: [-0.5, -0.5,  0.5], uv: [0.0, 1.0], color: [1.0, 0.0, 1.0] },
    ]
}